### ISSUE TITLE
undefined method `flush' for Logger

### ISSUE THREAD

**Issue by paneq** [chilloutio/chillout#1]
``` ruby
require 'chillout/creations_container'
require 'chillout/config'
require 'chillout/client'

creations = Chillout::CreationsContainer.new
creations.increment!("AAAAAA")

config = Chillout::Config.new("API_KEY")
config.ssl = false
config.port = "8080"
config.hostname = "localhost"


client = Chillout::Client.new(config)
client.enqueue(creations)
```

Happens when using default `Logger` from `Chillout::Config`

```
irb(main):059:0> I, [2013-04-18T17:35:00.836283 #23500]  INFO -- : [Chillout] Worker started
I, [2013-04-18T17:35:00.854312 #23500]  INFO -- : [Chillout] Sending startup message
I, [2013-04-18T17:35:00.854528 #23500]  INFO -- : [Chillout] Waiting for at least one container.
I, [2013-04-18T17:35:00.854685 #23500]  INFO -- : [Chillout] Received at least one container.
I, [2013-04-18T17:35:00.854939 #23500]  INFO -- : [Chillout] Received containers to process: 1
I, [2013-04-18T17:35:00.855121 #23500]  INFO -- : [Chillout] Trying to send creations
I, [2013-04-18T17:35:00.874123 #23500]  INFO -- : [Chillout] Metrics sent
/home/rupert/binary/ruby-1.9.3-p194-host/lib/ruby/gems/1.9.1/gems/chillout-0.6.0/lib/chillout/client.rb:56:in `ensure in block (2 levels) in start_worker': undefined method `flush' for #<Logger:0x00000002301400> (NoMethodError)
    from /home/rupert/binary/ruby-1.9.3-p194-host/lib/ruby/gems/1.9.1/gems/chillout-0.6.0/lib/chillout/client.rb:56:in `block (2 levels) in start_worker'
```

**Comment by paneq** [comment]
`1.9.3p194`

**Comment by mostlyobvious** [comment]
http://api.rubyonrails.org/classes/ActiveSupport/BufferedLogger.html#method-i-flush but no flush in standard logger
